apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: cloudtrace-exporter-sinkbinding
  namespace: default
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app: cloudtrace-exporter
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display